### ISSUE TITLE
Issue in accessing the Dataset

### ISSUE THREAD

**Issue by ok-kewei** [Ephemeral182/ECCV24_T3-DiffWeather#4]
Hi, I'm interested to know your result particularly in Raindrop. There's a bunch of Raindrop images in Visual Results (I believe they are results (images) after the model). Hence, i would to know how the original Raindrop images (before model) look like. Are they stored under the Dataset section? Nonetheless, I have difficulty in accessing the dataset (the link led me to baidu, which i don't have the access to baidu due to the regional restriction). May I humbly request you to send me the Raindrop dataset ? Hope to hear from you soon. Thank you.

**Comment by Ephemeral182** [comment]
Hi, thanks for your attention. You can use these links to obtain Raindrop-related benchmarks, which are from Google drive: [Raindrop-CCN](https://github.com/Songforrr/RainDS_CCN?tab=readme-ov-file) and [AGAN(Raindrop in our paper)](https://github.com/rui1996/DeRaindrop)

**Comment by ok-kewei** [comment]
Hi @Ephemeral182 , thanks for your prompt reply. I got the dataset. 
1. However, if i refer to the Raindrop images in Visual Results section (https://drive.google.com/drive/folders/1yDMkMICk_A3m_EIU8mz5zw84ubDGjAbm), which I believe they are results (images) after the model, right?
2. If yes, may i know where the respective images before the model of them. I just wanna see the improvement of raindrop removal with the before and after images.

Thank you so much :)

**Comment by Ephemeral182** [comment]
Hi, for your question:

1. Yes. This link provided includes the results from our model.

2. The Testing Set A of AGAN refers to the original images that you may need.
